### ISSUE TITLE
"Sorry, trouble retrieving payment receipt" shown since 2.5 for some customers

### ISSUE THREAD

**Issue by pippinsplugins** [easydigitaldownloads/Easy-Digital-Downloads#4160]
We've now had at least 4 reports of the `Sorry, trouble retrieving payment receipt` message being shown to customers after completing a purchase. I have not yet tracked down why this happens nor have I replicated it. I tested on one of the sites that reported having the problem and did not replicate it.

Reports:
https://wordpress.org/support/topic/problem-in-v253
https://wordpress.org/support/topic/sorry-trouble-retrieving-payment-receipt-error-message-for-logged-in-user
https://secure.helpscout.net/conversation/159039022/24894/?folderId=180504

**Comment by mindctrl** [comment]
https://secure.helpscout.net/conversation/159234868/24944/?folderId=180504

**Comment by cklosowski** [comment]
We should be paying close attention to session management on these. The redirect to the success page looks to 3 places for a payment key (which is missing when this error is shown). First it looks to the query string, then to the passed arguments, then to the session.
```
	$session = edd_get_purchase_session();
	if ( isset( $_GET['payment_key'] ) ) {
		$payment_key = urldecode( $_GET['payment_key'] );
	} elseif ( $edd_receipt_args['payment_key'] ) {
		$payment_key = $edd_receipt_args['payment_key'];
	} else if ( $session ) {
		$payment_key = $session['purchase_key'];
	}
```

**Comment by pippinsplugins** [comment]
This may be resolved with #4168

**Comment by pippinsplugins** [comment]
This user does NOT use buy now buttons and payments are marked as complete: https://wordpress.org/support/topic/sorry-trouble-retrieving-payment-receipt-error-message-for-logged-in-user?replies=4#post-7874561

**Comment by pippinsplugins** [comment]
I suspect this is also related to timezones.

**Comment by mindctrl** [comment]
I tried a bunch of timezone settings yesterday but couldn't replicate.

**Comment by pippinsplugins** [comment]
#4178

**Comment by pippinsplugins** [comment]
Fixed (we think) with #4178. If we see any new reports of this after 2.5.5, we'll re-open.

**Comment by upsellpl** [comment]
Hi,

I've got this problem on EDD 2.5.16 + EDD Auto Register 1.3.5 + Vendd on first purchase (new user).

**Comment by pippinsplugins** [comment]
Hi there!

Please go ahead and open a support ticket through our support portal: https://easydigitaldownloads.com/support

we use GitHub for development tracking only.

**Comment by TheCrowned** [comment]
This looks to be still an issue:
https://wordpress.org/support/topic/sorry-trouble-retrieving-payment-receipt-2/

I am also experiencing it.

(I would file a support ticket, but the last one a few weeks ago, about a non-related matter, never got a reply, so...)

**Comment by ashleyfae** [comment]
@TheCrowned This is an issue with sessions. Please do try submitting a support ticket again so our team can assist you: https://easydigitaldownloads.com/support I'm sorry that you didn't hear back from the last ticket -- I'm not sure what may have happened there. If you don't receive a reply this time please let us know.
