### ISSUE TITLE
3.0 - Advanced Sequential Order Numbers are not overriding Sequential Order Numbers.

### ISSUE THREAD

**Issue by mintplugins** [easydigitaldownloads/easy-digital-downloads#7315]
### Expected behavior
When I have [Advanced Sequential Order Numbers](https://easydigitaldownloads.com/downloads/advanced-sequential-order-numbers/) activated and enabled, I expect the `order_number` column in the `orders` table to be populated with the value from `Advanced Sequential Order Numbers`. 

### Actual behavior
The `order_number` column is populated with the value from EDD core's `Sequential Order Numbers` option, instead of the value from the `Advanced Sequential Order Numbers` extension.

The reason I am logging this here (on the EDD core repo) is to investigate whether this is a breakdown in backwards compatibility in EDD core or not. 

### Steps to reproduce the behavior
1) Enable both `Sequential Order Numbers` and `Advanced Sequential Order Numbers`. Set up a prefix for Advanced so that it's easy to determine whether it was used.
2) Make a purchase.
3) In the `orders` table, check the value in the order_number column.
4) Notice it does not have the prefix.

### Information (if a specific version is affected):
EDD Version (or branch): 3.0

**Comment by cklosowski** [comment]
We should verify this on 2.9.x as well.

**Comment by mintplugins** [comment]
I just verified that is the behaviour on 2.9.x: `Advanced Sequential Order Numbers` does override the `Sequential Order Numbers` settings for EDD core. So this is a regression.

**Comment by cklosowski** [comment]
@mintplugins While we investigate, we should determine if this is something that _should_ be fixed in ASON or in EDD Core. It's likely something changed in EDD Core, but previously ASON was 'accidentally' overriding.

Just keep in mind it might be the fault of ASON during investigating.

**Comment by mintplugins** [comment]
After digging into this, it's a bit of a doozie. While there are a few places where ASON needs `post` to be updated to `payment/order` (like "get_post" becoming "edd_get_payment"), ultimately those things are not the main cause.

ASON uses the action hook [edd_update_payment_status](https://github.com/easydigitaldownloads/easy-digital-downloads/blob/release/3.0/includes/payments/class-edd-payment.php#L1991) to add/update a meta key attached to the order called `_edd_son_payment_number`.

That is the only place where ASON stores its order number, and always has. That is fine.

EDD Core stores its Sequential Order Number in the `order_number` column of the orders table.  That is also fine.

Storing both order numbers doesn't really cause any problem, and is probably the way I would prefer to go since it avoids possible column->value collisions (I prefer having a single column for a single, unfiltered purpose whenever possible so the value is reliable). 

But EDD3 core is not showing the previously filtered-in order_number upon display. Rather, it completely ignores the `edd_payment_number` filter now. 

That's because for display, EDD core is calling [order->get_number()](https://github.com/easydigitaldownloads/easy-digital-downloads/blob/release/3.0/templates/shortcode-receipt.php#L32) everywhere it shows order IDs, and does not allow the value to be filtered, which is required for any extension to change that value.

There were 2 ways around this that I saw:
1. Go back to how things were in 2.9.x and use `$payment->number` everywhere upon display.
2. Keep using `order->get_number()` everywhere upon display, and add the `edd_payment_number` filter to the `get_number` method in `EDD\Orders\Order`.

I tried option 1. However, it required calling `edd_get_payment` in every single place where orders are shown, which goes against everything that EDD3 is trying to do with speeding up things. So after getting pretty deep with that approach I decided that's likely not what ya'll want.

Therefore, I believe our least backwards-breaking option here is to add the `edd_payment_number` filter to the return from the [order->get_number()](https://github.com/easydigitaldownloads/easy-digital-downloads/blob/release/3.0/templates/shortcode-receipt.php#L32) method. 

However, this will require us to release a breaking change to the `edd_payment_number` filter, and remove the last paramater from the filter, which is the EDD_Payment object. We will not have access to the EDD_Payment object from that filter anymore. 

There's also the possibility for an infinite loop if you call `edd_get_payment_meta` from inside the `edd_payment_number` hook, [which is what ASON currently does](https://github.com/easydigitaldownloads/edd-advanced-sequential-order-numbers/blob/master/edd-son.php#L180). That is because `edd_get_payment_meta` calls `EDD_Payment` which calls `$this->order->get_number()` which re-runs the filter which started it all, `edd_payment_number`. 

The way around that is to change the call from `edd_get_payment_meta` to be `edd_get_order_meta` in ASON, and anywhere else that might use the `edd_payment_number` hook.

If there's another way around this, I am all ears! But I really went deep on both of these approaches and found this to be the least probalematic, and the closest to our 3.0 goals.

**Comment by mintplugins** [comment]
Oh also, one other approach that I considered (call this #3) was literally storing the ason value in the order_number column. While this would work, it's a shift in how ASON works, and also doesn't solve the issue with the placement of the `edd_payment_number` filter (and that it is not longer being run in relevant places), which really ends up being the root issue here.

**Comment by mintplugins** [comment]
After discussing this with @cklosowski I am going to see if we can keep the filter in EDD_Payment, as well as in EDD_Order, but set up a flag so that it only runs once. Without the flag you end up with an infinite loop.

We'll attempt to do this with a static var in EDD_Order and put it in get_number like this:

```
 public function get_number() {
        static $number;

        if ( ! is_null( $number ) ) {
            return $number;
        }

        // Now run the filter.
```

**Comment by mintplugins** [comment]
Turns out we don't need to add it to EDD_Payment because EDD_Payment calls EDD/Orders/Order. So that is all fine. I did still add the flag though, as it prevents an infinite loop edge case that was happening in Advanced Sequential Order Numbers. Notes were left inline. This is likely a good thing to add in general for setters with filters.
